### ISSUE TITLE
Roadmap: 0.3.0

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/react-tv#50]
- [ ] Device keys  
- [ ] Focus logic(?)
- [ ] Propagate handler for keyboard on React.Elements.
- [ ] Think about `AppIsReady` for TVS. It's about done/loaded events which WebOS and Tizen dispatch, start mapping it in a HOC?
- [ ] add tests using Class based on `React.Component`
- [ ] finish basic CLI features for WebOS
  - [ ] `react-tv webos-log`
  - [ ] `react-tv init <app-name>`
 - [ ] documentation for WebOS 3.0 SDK Install
 - [ ] write tests for `run-webos`

**Comment by raphamorim** [comment]
Ref: #87

**Comment by raphamorim** [comment]
Ref: https://github.com/raphamorim/react-tv/pull/123
